// 커뮤니티 게시글 데이터 - 전역 공유용

/** 본문 텍스트·이미지 인터리브 (에디터 삽입 순서 유지) */
export type PostBodySegment =
  | { type: 'text'; text: string }
  | { type: 'image'; imageId: string };

export interface CommunityPost {
  id: string;
  userId: string;
  nickname?: string;          // 표시용 닉네임 (없으면 컴포넌트에서 '익명' 처리)
  userRole: 'patient' | 'caregiver';
  ageGroup?: string;
  department: string;
  disease?: string;
  condition?: string;
  emotion?: 'good' | 'normal' | 'bad' | 'very_bad';
  title: string;
  summary: string;
  /** 본문 세그먼트(있으면 표시 시 이 순서를 우선). 없으면 summary + attachedImages 하단 나열(구버전) */
  bodySegments?: PostBodySegment[];
  aiLabel: string;
  likeCount: number;
  comments: number;
  views: number;
  timeAgo: string;
  isLiked?: boolean;
  isVerified?: boolean;
  /** 게시글에 언급된 의사 이름 목록 (검색·연결용) */
  relatedDoctors?: string[];
  /** 첨부 이미지 (base64 또는 URL) */
  attachedImages?: { id: string; url: string; name: string; thumbnail: string }[];
  /** 수정 여부 */
  isEdited?: boolean;
  /** 수정 일시 (ISO 8601) */
  editedAt?: string;
}

/** 검색·미리보기용 평문 (bodySegments가 있으면 그 텍스트만 합침) */
export function postPlainBodyText(post: Pick<CommunityPost, 'summary' | 'bodySegments'>): string {
  if (post.bodySegments?.length) {
    const t = post.bodySegments
      .filter((s): s is { type: 'text'; text: string } => s.type === 'text')
      .map(s => s.text)
      .join('');
    return t.replace(/\u200b/g, '').trim();
  }
  return post.summary;
}

// 랜덤 게시글 반환 헬퍼 (구버전 getRandomCommunityPost 대체)
export function getRandomCommunityPost(): CommunityPost {
  const idx = Math.floor(Math.random() * communityPosts.length);
  return communityPosts[idx];
}

export const communityPosts: CommunityPost[] = [
  {
    id: 'demo-no-comments',
    userId: 'user_demo_empty',
    nickname: '건강기록장',
    userRole: 'patient',
    department: '내과',
    disease: '감기',
    emotion: 'normal',
    title: '[샘플] 아직 댓글이 없는 글이에요',
    summary:
      '커뮤니티 상세(PostDetailModal)에서 댓글이 0일 때 안내 문구를 확인하기 위한 더미 글입니다. 아래에 "첫 댓글을 작성해보세요"가 보여야 합니다.',
    aiLabel: '일반 후기',
    likeCount: 4,
    comments: 0,
    views: 56,
    timeAgo: '3시간 전',
    isVerified: false,
  },
  {
    id: '1',
    userId: 'user1',
    nickname: '하늘별빛',
    userRole: 'caregiver',
    ageGroup: '아동(0-12세)',
    department: '소아과',
    disease: '열성경련',
    emotion: 'bad',
    title: '밤새 열나던 아이, 새벽에 응급실 가야하나 고민했는데...',
    summary: 'AI가 열성경련 가능성을 체크해줘서 바로 응급실 갔어요. 다행히 빨리 조치받아서 괜찮아졌습니다. 정말 다급한 순간에 AI가 큰 도움이 됐어요.',
    aiLabel: 'AI 증세체크 후 실제 진료 후기',
    likeCount: 120,
    comments: 8,
    views: 1520,
    timeAgo: '2시간 전',
    isVerified: true,
    attachedImages: [
      {
        id: 'img-1-1',
        url: 'https://images.unsplash.com/photo-1721114989769-0423619f03d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3NwaXRhbCUyMGVtZXJnZW5jeSUyMHJvb218ZW58MXx8fHwxNzczNjI5MjA4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '응급실.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1721114989769-0423619f03d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob3NwaXRhbCUyMGVtZXJnZW5jeSUyMHJvb218ZW58MXx8fHwxNzczNjI5MjA4fDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '2',
    userId: 'user2',
    nickname: '새벽이슬',
    userRole: 'patient',
    department: '내과',
    disease: '역류성식도염',
    emotion: 'normal',
    title: '3주째 속쓰림... 스트레스인 줄 알았는데 역류성식도염이었어요',
    summary: 'AI 진단에서 역류성식도염 의심 판정 받고 추천받은 소화기내과 전문의한테 갔더니 정확했어요. 약 처방받고 일주일만에 많이 좋아졌습니다.',
    aiLabel: 'AI 추천 병원 방문 경험',
    likeCount: 85,
    comments: 5,
    views: 892,
    timeAgo: '5시간 전',
    isVerified: true,
    isEdited: true,
    editedAt: '2026-03-12T09:30:00.000Z',
    attachedImages: [
      {
        id: 'img-2-1',
        url: 'https://images.unsplash.com/photo-1550572017-54b7f54d1f75?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwcHJlc2NyaXB0aW9uJTIwcmVjZWlwdHxlbnwxfHx8fDE3NzM2NDc5NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '처방전.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1550572017-54b7f54d1f75?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwcHJlc2NyaXB0aW9uJTIwcmVjZWlwdHxlbnwxfHx8fDE3NzM2NDc5NTJ8MA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
      {
        id: 'img-2-2',
        url: 'https://images.unsplash.com/photo-1646392206581-2527b1cae5cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2luZSUyMHBpbGxzJTIwcGhhcm1hY3l8ZW58MXx8fHwxNzczNTk5OTY5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '약.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1646392206581-2527b1cae5cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2luZSUyMHBpbGxzJTIwcGhhcm1hY3l8ZW58MXx8fHwxNzczNTk5OTY5fDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '3',
    userId: 'user3',
    nickname: '희망이님',
    userRole: 'patient',
    department: '정신과',
    disease: '공황장애',
    emotion: 'good',
    title: '공황장애로 3년 고생... 드디어 나에게 맞는 치료법을 찾았어요',
    summary: '여러 병원을 전전하다가 Aiga에서 강지은 교수님을 추천받았고, 6개월간의 치료 끝에 많이 회복됐습니다. 가톨릭대학교병원까지 좀 멀었는데 그만한 가치가 있었어요. 포기하지 않으시길!',
    aiLabel: 'AI 명의 추천 성공 사례',
    likeCount: 220,
    comments: 9,
    views: 2130,
    timeAgo: '1일 전',
    isVerified: true,
    relatedDoctors: ['강지은'],
    attachedImages: [
      {
        id: 'img-3-1',
        url: 'https://images.unsplash.com/photo-1758691462126-2ee47c8bf9e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2N0b3IlMjBjb25zdWx0YXRpb24lMjBob3NwaXRhbHxlbnwxfHx8fDE3NzM2MjA4OTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '상담.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1758691462126-2ee47c8bf9e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb2N0b3IlMjBjb25zdWx0YXRpb24lMjBob3NwaXRhbHxlbnwxfHx8fDE3NzM2MjA4OTF8MA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '4',
    userId: 'user4',
    nickname: '봄날의곰',
    userRole: 'patient',
    department: '정형외과',
    disease: '허리디스크',
    emotion: 'normal',
    title: '허리디스크 재발... 재수술 고민 중이에요',
    summary: '2년 전 수술했는데 다시 아파서 걱정이 많네요. 같은 경험 있으신 분 조언 부탁드려요.',
    aiLabel: '재수술 상담 요청',
    likeCount: 58,
    comments: 6,
    views: 654,
    timeAgo: '1일 전',
    isVerified: false,
  },
  {
    id: '5',
    userId: 'user5',
    nickname: '긍정왕',
    userRole: 'caregiver',
    ageGroup: '청소년(13-18세)',
    department: '피부과',
    disease: '아토피',
    emotion: 'good',
    title: '중3 딸 아토피가 1년 만에 완치됐어요!',
    summary: 'Aiga에서 임준영 교수님(세브란스병원 피부과)을 추천받아 꾸준히 치료받았더니 정말 좋아졌어요. 같은 고민 있는 부모님들 희망 가지세요!',
    aiLabel: '장기 치료 성공 후기',
    likeCount: 165,
    comments: 7,
    views: 1876,
    timeAgo: '2일 전',
    isVerified: true,
    relatedDoctors: ['임준영'],
  },
  {
    id: '6',
    userId: 'user6',
    nickname: '민들레꽃',
    userRole: 'patient',
    department: '내과',
    disease: '당뇨',
    emotion: 'normal',
    title: '당뇨 진단 받고 3개월... 혈당 관리 팁 공유합니다',
    summary: '식단 조절이 제일 중요하더라고요. 앱에서 추천받은 영양사 상담도 많은 도움이 됐어요. 혈당이 많이 안정됐습니다.',
    aiLabel: '당뇨 관리 노하우',
    likeCount: 92,
    comments: 5,
    views: 743,
    timeAgo: '3일 전',
    isVerified: false,
    attachedImages: [
      {
        id: 'img-6-1',
        url: 'https://images.unsplash.com/photo-1707529172036-fb5ffbc70bf8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwZm9vZCUyMG1lYWx8ZW58MXx8fHwxNzczNTY5MDI5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '건강식단1.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1707529172036-fb5ffbc70bf8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwZm9vZCUyMG1lYWx8ZW58MXx8fHwxNzczNTY5MDI5fDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
      {
        id: 'img-6-2',
        url: 'https://images.unsplash.com/photo-1576669801775-ff43c5ab079d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdGVzdCUyMHJlc3VsdHN8ZW58MXx8fHwxNzczNjQ3OTU0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '혈당측정기.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1576669801775-ff43c5ab079d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwdGVzdCUyMHJlc3VsdHN8ZW58MXx8fHwxNzczNjQ3OTU0fDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
      {
        id: 'img-6-3',
        url: 'https://images.unsplash.com/photo-1646392206581-2527b1cae5cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2luZSUyMHBpbGxzJTIwcGhhcm1hY3l8ZW58MXx8fHwxNzczNTk5OTY5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '당뇨약.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1646392206581-2527b1cae5cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2luZSUyMHBpbGxzJTIwcGhhcm1hY3l8ZW58MXx8fHwxNzczNTk5OTY5fDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '7',
    userId: 'user7',
    nickname: '알뜰왕',
    userRole: 'caregiver',
    ageGroup: '노인(65세 이상)',
    department: '내과',
    disease: '고혈압',
    emotion: 'good',
    title: '아버지 고혈압 약 바꾸고 나서 많이 좋아지셨어요',
    summary: 'Aiga에서 추천받은 김민수 교수님(서울아산병원 순환기내과)이 정말 꼼꼼하게 봐주셔서 감사했습니다. 부작용도 줄고 혈압도 안정됐어요.',
    aiLabel: 'AI 명의 추천 후기',
    likeCount: 134,
    comments: 6,
    views: 1024,
    timeAgo: '3일 전',
    isVerified: true,
    relatedDoctors: ['김민수'],
  },
  {
    id: '8',
    userId: 'user8',
    nickname: '강한언니',
    userRole: 'patient',
    department: '이비인후과',
    disease: '비염',
    emotion: 'normal',
    title: '만성 비염으로 10년... 수술 고민중입니다',
    summary: '약물치료는 한계가 있는 것 같아서 수술을 생각하고 있어요. 수술 경험 있으신 분들 후기 부탁드려요.',
    aiLabel: '수술 정보 요청',
    likeCount: 45,
    comments: 8,
    views: 567,
    timeAgo: '4일 전',
    isVerified: false,
  },
  {
    id: '9',
    userId: 'user9',
    nickname: '희망나무',
    userRole: 'patient',
    department: '내과',
    disease: '위염',
    emotion: 'bad',
    title: '만성위염 때문에 밥 먹는게 너무 힘들어요',
    summary: '스트레스 받으면 바로 속이 쓰리고... 어떻게 관리하시나요? 좋은 병원이나 관리법 있으면 공유해주세요.',
    aiLabel: '위염 관리 고민',
    likeCount: 67,
    comments: 7,
    views: 823,
    timeAgo: '4일 전',
    isVerified: false,
  },
  {
    id: '10',
    userId: 'user10',
    nickname: '구름위에서',
    userRole: 'caregiver',
    ageGroup: '성인(19-64세)',
    department: '외과',
    disease: '유방암',
    emotion: 'good',
    title: '엄마 유방암 수술 성공적으로 끝났습니다',
    summary: 'Aiga에서 추천받은 이서연 교수님(삼성서울병원 유방외과)이 정말 실력이 좋으셨어요. 수술도 잘 끝나고 예후도 좋다고 하십니다. 감사합니다.',
    aiLabel: 'AI 명의 추천 감사 후기',
    likeCount: 312,
    comments: 10,
    views: 2847,
    timeAgo: '5일 전',
    isVerified: true,
    relatedDoctors: ['이서연'],
  },
  {
    id: '11',
    userId: 'user3',
    nickname: '희망이님',
    userRole: 'patient',
    department: '정신과',
    disease: '우울증',
    emotion: 'normal',
    title: '항우울제 복용 시작한지 2주차 후기',
    summary: '아직 극적인 변화는 없지만 조금씩 나아지는 느낌이에요. 꾸준히 치료받는게 중요하다고 하네요.',
    aiLabel: '우울증 치료 경과',
    likeCount: 78,
    comments: 5,
    views: 692,
    timeAgo: '5일 전',
    isVerified: false,
  },
  {
    id: '12',
    userId: 'user11',
    nickname: '은빛달빛',
    userRole: 'patient',
    department: '정형외과',
    disease: '관절',
    emotion: 'bad',
    title: '무릎 관절염으로 계단 오르기가 너무 힘듭니다',
    summary: '나이가 들면서 점점 심해지는 것 같아요. 인공관절 수술 하신 분들 계신가요?',
    aiLabel: '관절염 수술 문의',
    likeCount: 53,
    comments: 8,
    views: 621,
    timeAgo: '6일 전',
    isVerified: false,
  },
  {
    id: '13',
    userId: 'user12',
    nickname: '행복한부모',
    userRole: 'caregiver',
    ageGroup: '아동(0-12세)',
    department: '소아과',
    disease: '천식',
    emotion: 'normal',
    title: '7살 아들 천식 진단... 앞으로 어떻게 관리해야 할까요',
    summary: '환절기만 되면 기침을 심하게 해서 병원 갔더니 천식이라고 하네요. 같은 경험 있으신 부모님들 조언 부탁드려요.',
    aiLabel: '소아 천식 관리 질문',
    likeCount: 89,
    comments: 9,
    views: 934,
    timeAgo: '6일 전',
    isVerified: false,
  },
  {
    id: '14',
    userId: 'user13',
    nickname: '파란하늘',
    userRole: 'patient',
    department: '외과',
    disease: '갑상선암',
    emotion: 'good',
    title: '갑상선암 수술 후 1년, 재발 없이 건강합니다',
    summary: 'Aiga에서 추천받은 박지훈 교수님(세브란스병원 내분비외과)을 만나서 잘 치료받았어요. 같은 병으로 힘들어하시는 분들 힘내세요!',
    aiLabel: '암 완치 후기',
    likeCount: 278,
    comments: 10,
    views: 3124,
    timeAgo: '1주일 전',
    isVerified: true,
    relatedDoctors: ['박지훈'],
  },
  {
    id: '15',
    userId: 'user14',
    nickname: '봄꽃처럼',
    userRole: 'patient',
    department: '산부인과',
    disease: '난임',
    emotion: 'very_bad',
    title: '시험관 3번째 실패... 너무 힘드네요',
    summary: '경제적으로도 정신적으로도 너무 힘듭니다. 같은 경험 있으신 분들 어떻게 극복하셨나요?',
    aiLabel: '난임 치료 고민',
    likeCount: 156,
    comments: 10,
    views: 1243,
    timeAgo: '1주일 전',
    isVerified: false,
  },
  {
    id: '20',
    userId: 'user18',
    nickname: '용감한전사',
    userRole: 'patient',
    department: '외과',
    disease: '대장암',
    emotion: 'good',
    title: '대장암 3기 판정 받았지만 포기하지 않겠습니다',
    summary: 'Aiga에서 추천받은 최유진 교수님(서울대학교병원 대장항문외과)께 수술받고 항암치료 시작했어요. 힘들지만 이겨낼 수 있다고 믿습니다.',
    aiLabel: 'AI 명의 추천 + 투병 시작',
    likeCount: 425,
    comments: 10,
    views: 4326,
    timeAgo: '2주일 전',
    isVerified: true,
    relatedDoctors: ['최유진'],
  },
  {
    id: '25',
    userId: 'user22',
    nickname: '따뜻한손길',
    userRole: 'caregiver',
    ageGroup: '성인(19-64세)',
    department: '신경과',
    disease: '뇌졸중',
    emotion: 'normal',
    title: '남편 뇌졸중으로 쓰러지고 재활 중입니다',
    summary: '골든타임에 병원 도착해서 후유증은 크지 않은데, 재활이 생각보다 오래 걸리네요. 재활 잘 하신 분들 경험담 듣고 싶어요.',
    aiLabel: '뇌졸중 재활 경험',
    likeCount: 124,
    comments: 9,
    views: 1087,
    timeAgo: '3주일 전',
    isVerified: false,
  },

  // ── 간암 ──────────────────────────────────────────────────
  {
    id: '26',
    userId: 'user23',
    nickname: '새벽노을',
    userRole: 'patient',
    department: '소화기내과',
    disease: '간암',
    emotion: 'bad',
    title: 'B형 간염 보유자인데 간암 초기 발견됐어요',
    summary: 'Aiga에서 추천받은 형채윤 교수님(서울아산병원 소화기내과)께 진료받았어요. 초기라 다행이지만 너무 무서웠습니다. 간경변 있으신 분들 꼭 정기검진 으세요.',
    aiLabel: 'AI 명의 추천 + 조기발견 후기',
    likeCount: 203,
    comments: 10,
    views: 2341,
    timeAgo: '4일 전',
    isVerified: true,
    relatedDoctors: ['형채윤'],
  },
  {
    id: '27',
    userId: 'user24',
    nickname: '밝은내일',
    userRole: 'patient',
    department: '외과',
    disease: '간암',
    emotion: 'good',
    title: '간암 수술 후 6개월... 정기검사 결과 공유합니다',
    summary: '세브란스병원 선유나 교수님께 간절제술 받고 반년이 지났어요. 지난주 CT에서 재발 소견 없다는 결과 받았습니다. 힘드셨던 분들께 희망이 됐으면 해요.',
    aiLabel: '간암 수술 6개월 후기',
    likeCount: 318,
    comments: 10,
    views: 3890,
    timeAgo: '1주일 전',
    isVerified: true,
    relatedDoctors: ['선유나'],
    attachedImages: [
      {
        id: 'img-27-1',
        url: 'https://images.unsplash.com/photo-1620423855978-e5d74a7bef30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIweHJheSUyMHNjYW58ZW58MXx8fHwxNzczNjMyNjEwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: 'CT촬영결과.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1620423855978-e5d74a7bef30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIweHJheSUyMHNjYW58ZW58MXx8fHwxNzczNjMyNjEwfDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '28',
    userId: 'user25',
    nickname: '기다리는봄',
    userRole: 'caregiver',
    ageGroup: '노인(65세 이상)',
    department: '외과',
    disease: '간암',
    emotion: 'very_bad',
    title: '아버지 간이식 대기 중... 너무 막막합니다',
    summary: '간암 말기로 간이식만이 답이라는 진단을 받았어요. 분당서울대병원 우예원 교수님이 최선을 다해주신다고 하시는데 대기 기간이 너무 길어서 걱정됩니다.',
    aiLabel: '간이식 대기 중 고민',
    likeCount: 176,
    comments: 10,
    views: 2104,
    timeAgo: '3일 전',
    isVerified: false,
    relatedDoctors: ['우예원'],
  },
  {
    id: '33',
    userId: 'user30',
    nickname: '씩씩한걸음',
    userRole: 'patient',
    department: '소화기내과',
    disease: '간암',
    emotion: 'normal',
    title: '간암 항암치료 2차까지 마쳤어요 — 부작용 솔직 후기',
    summary: '소라페닙 복용하면서 손발 피부 부작용이 생각보다 심했어요. 삼성서울병원 김하영 교수님이 용량 조절해주셔서 지금은 많이 나아졌습니다. 같은 치료 받으시는 분들 참고하세요.',
    aiLabel: '간암 항암 부작용 실전 후기',
    likeCount: 147,
    comments: 10,
    views: 1823,
    timeAgo: '2일 전',
    isVerified: true,
    relatedDoctors: ['김하영'],
  },
  {
    id: '34',
    userId: 'user31',
    nickname: '작은기적',
    userRole: 'caregiver',
    ageGroup: '성인(19-64세)',
    department: '외과',
    disease: '간암',
    emotion: 'good',
    title: '남편 간세포암 2기, TACE 시술 후 종양이 작아졌어요!',
    summary: '서울아산병원에서 간동맥화학색전술(TACE) 받고 3개월 뒤 MRI 찍었더니 종양 크기가 절반으로 줄었다는 결과가 나왔어요. 포기하지 마시고 좋은 선생님을 찾아보세요.',
    aiLabel: '간암 TACE 시술 효과 후기',
    likeCount: 265,
    comments: 10,
    views: 3047,
    timeAgo: '6일 전',
    isVerified: true,
    relatedDoctors: [],
  },

  // ── 척추 ──────────────────────────────────────────────────
  {
    id: '29',
    userId: 'user26',
    nickname: '꺾이지않는나무',
    userRole: 'patient',
    department: '정형외과',
    disease: '척추측만증',
    emotion: 'good',
    title: '척추측만증 수술 후 1년, 이제 정말 괜찮아요',
    summary: '한양대학교병원 한지호 교수님께 척추측만증 교정수술을 받았어요. 수술 전에는 37도였는데 지금은 8도로 줄었습니다. 많이 망설이셨던 분들 용기 내세요!',
    aiLabel: '척추측만증 수술 성공 후기',
    likeCount: 241,
    comments: 10,
    views: 2876,
    timeAgo: '5일 전',
    isVerified: true,
    relatedDoctors: ['한지호'],
  },
  {
    id: '30',
    userId: 'user27',
    nickname: '고민중입니다',
    userRole: 'patient',
    department: '정형외과',
    disease: '척추관협착증',
    emotion: 'normal',
    title: '척추관협착증, 비수술 치료와 수술 사이에서 고민입니다',
    summary: '경희대학교병원 오서현 교수님께서 아직 비수술로 해볼 여지가 있다고 하시는데, 주사 치료 받으시다 결국 수술하신 분들 계신가요? 경험담이 너무 궁금해요.',
    aiLabel: '척추 치료 고민 상담',
    likeCount: 98,
    comments: 10,
    views: 1432,
    timeAgo: '2일 전',
    isVerified: false,
    relatedDoctors: ['오서현'],
  },

  // ── 허리디스크 ────────────────────────────────────────────
  {
    id: '31',
    userId: 'user28',
    nickname: '완치의기쁨',
    userRole: 'patient',
    department: '신경외과',
    disease: '허리디스크',
    emotion: 'good',
    title: '허리디스크 6개월 치료 끝에 드디어 완치 판정!',
    summary: 'Aiga에서 추천받은 고려대학교병원 조현서 교수님 덕분에 수술 없이 나았어요. 처음엔 다리까지 저렸는데 물리치료 + 주사 병행하니 정말 좋아졌습니다.',
    aiLabel: '허리디스크 비수술 완치 후기',
    likeCount: 289,
    comments: 10,
    views: 3210,
    timeAgo: '4일 전',
    isVerified: true,
    relatedDoctors: ['조현서'],
    attachedImages: [
      {
        id: 'img-31-1',
        url: 'https://images.unsplash.com/photo-1545463913-5083aa7359a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaHlzaWNhbCUyMHRoZXJhcHklMjByZWhhYmlsaXRhdGlvbnxlbnwxfHx8fDE3NzM2MTk5NDF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: '물리치료.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1545463913-5083aa7359a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaHlzaWNhbCUyMHRoZXJhcHklMjByZWhhYmlsaXRhdGlvbnxlbnwxfHx8fDE3NzM2MTk5NDF8MA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
      {
        id: 'img-31-2',
        url: 'https://images.unsplash.com/photo-1620423855978-e5d74a7bef30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIweHJheSUyMHNjYW58ZW58MXx8fHwxNzczNjMyNjEwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
        name: 'MRI결과.jpg',
        thumbnail: 'https://images.unsplash.com/photo-1620423855978-e5d74a7bef30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIweHJheSUyMHNjYW58ZW58MXx8fHwxNzczNjMyNjEwfDA&ixlib=rb-4.1.0&q=80&w=200&utm_source=figma&utm_medium=referral',
      },
    ],
  },
  {
    id: '32',
    userId: 'user29',
    nickname: '허리아파요',
    userRole: 'patient',
    department: '신경외과',
    disease: '허리디스크',
    emotion: 'bad',
    title: 'MRI 결과 허리디스크 3개... 수술 꼭 해야 할까요?',
    summary: '갑자기 허리를 삐끗한 뒤로 앉기가 너무 힘들어요. 신경이 눌려 있다고 해서 걱정인데, 디스크 수술 경험 있으신 분들 회복 기간이 어떻게 됐나요?',
    aiLabel: '허리디스크 수술 고민',
    likeCount: 134,
    comments: 10,
    views: 1876,
    timeAgo: '1일 전',
    isVerified: false,
  },
];